networks:
  app-network:
    driver: bridge

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  python-api:
    build: ./pythonapi
    container_name: python-api
    restart: unless-stopped
    environment:
      DB_HOST: mysql-db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
    depends_on:
      - mysql-db
    networks:
      - app-network

  react-app:
    build: ./reactapp
    container_name: react-app
    restart: unless-stopped
    networks:
      - app-network

  nginx-proxy:
    build: ./proxy
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - python-api
      - react-app
    networks:
      - app-network

volumes:
  mysql-data:
